name: Release

## TODO: Activate
# on:
#   push:
#     branches: master

## TODO: Remove
on:
  push:
    branches-ignore:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2.5.0
        with:
          node-version: 14
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: bahmutov/npm-install@v1
      - run: npm t

  version:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2.5.0
        with:
          node-version: 14
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: bahmutov/npm-install@v1

      - name: Bump version and push tag
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          preset: 'conventionalcommits'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-message: 'chore(release): {version} [skip ci]'
          git-user-name: 'Simone Corsi'
          git-user-email: 'simonecorsi.dev@gmail.com'
          tag-prefix: ''

      - name: Create github Release
        uses: actions/create-release@master
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.changelog }}

      - name: NPM Publish
        uses: JS-DevTools/npm-publish@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        with:
          token: ${{ secrets.npm_token }}
          access: 'public'
